//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dino.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string themes {
            get {
                return ((string)(this["themes"]));
            }
            set {
                this["themes"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""label"":""Cartão 001"",""id"":""862721FE""},{""label"":""Cartão 002"",""id"":""E3B5351E""},{""label"":""Cartão 003"",""id"":""A3F50F55""},{""label"":""Cartão 004"",""id"":""E6EB26FE""},{""label"":""Cartão 005"",""id"":""B6C66BFE""},{""label"":""Cartão 006"",""id"":""63D8E554""},{""label"":""Cartão 007"",""id"":""461538FE""},{""label"":""Cartão 008"",""id"":""464560FE""},{""label"":""Cartão 009"",""id"":""338AEA54""},{""label"":""Cartão 010"",""id"":""96AE2BFE""},{""label"":""Cartão 011"",""id"":""D68E54FE""},{""label"":""Cartão 012"",""id"":""265D50FE""},{""label"":""Cartão 013"",""id"":""26C049FE""},{""label"":""Cartão 014"",""id"":""F6AEF5FD""},{""label"":""Cartão 015"",""id"":""A3AE0D55""},{""label"":""Cartão 016"",""id"":""76B212FE""},{""label"":""Cartão 017"",""id"":""237D0C55""},{""label"":""Cartão 018"",""id"":""E61725FE""},{""label"":""Cartão 019"",""id"":""A6D918FE""},{""label"":""Cartão 020"",""id"":""F3EDE054""},{""label"":""Cartão 021"",""id"":""D34B0D55""},{""label"":""Cartão 022"",""id"":""83490F55""},{""label"":""Cartão 023"",""id"":""966C63FE""},{""label"":""Cartão 024"",""id"":""565B50FE""},{""label"":""Cartão 025"",""id"":""F62825FE""}]")]
        public string tags {
            get {
                return ((string)(this["tags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int next_slide_delay {
            get {
                return ((int)(this["next_slide_delay"]));
            }
        }
    }
}
