//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dino.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string themes {
            get {
                return ((string)(this["themes"]));
            }
            set {
                this["themes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""label"":""Cartao 1"",""id"":""862721FE""},{""label"":""Cartao 2"",""id"":""E3B5351E""},{""label"":""Cartao 3"",""id"":""A3F50F55""},{""label"":""Cartao 4"",""id"":""E6EB26FE""},{""label"":""Cartao 5"",""id"":""B6C66BFE""},{""label"":""Cartao 6"",""id"":""63D8E554""},{""label"":""Cartao 7"",""id"":""461538FE""},{""label"":""Cartao 8"",""id"":""464560FE""},{""label"":""Cartao 9"",""id"":""338AEA54""},{""label"":""Cartao 10"",""id"":""96AE2BFE""},{""label"":""Cartao 11"",""id"":""D68E54FE""}]")]
        public string tags {
            get {
                return ((string)(this["tags"]));
            }
            set {
                this["tags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cards_count {
            get {
                return ((int)(this["cards_count"]));
            }
            set {
                this["cards_count"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int next_slide_delay {
            get {
                return ((int)(this["next_slide_delay"]));
            }
        }
    }
}
